apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-relic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm-charts.newrelic.com
      chart: nri-bundle
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/manifests/newrelic-values.yaml
    - repoURL: https://github.com/faulty-technology/talos-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: newrelic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
